language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
env:
  - CODECOV_TOKEN='bd000f2f-4e22-4471-87a9-e6459ebdec7d'
install:
  - pip install pytest coverage
  - pip install .
script:
  - coverage run -m pytest
after_script:
  - coverage xml
after_success:
  - bash <(curl -s https://codecov.io/bash)