language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
env:
  - CODACY_API_BASE_URL='066ab3574e79454188d5c0cd472136dd'
install:
  - pip install pytest coverage
  - pip install .
script:
  - coverage run -m pytest
after_script:
  - coverage xml
after_success:
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) coverage.xml